services:
  - type: web
    name: ecommerce-admin
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: ecommerce-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ecommerce-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ecommerce-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: ecommerce-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ecommerce-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        generateValue: true

databases:
  - name: ecommerce-db
    databaseName: ecommerce_admin
    user: ecommerce_user